{{- if and .Values.secrets.create .Values.secrets.gcpServiceAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightspeed-agent.fullname" . }}-gcp-sa-key
  labels:
    {{- include "lightspeed-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  sa-key.json: {{ .Values.secrets.gcpServiceAccountKey | quote }}
{{- end }}
