{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}-gcp-secrets
  namespace: {{ include "chart.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ include "chart.fullname" . }}-gcp-sm
    kind: SecretStore
  target:
    name: {{ include "chart.fullname" . }}-gcp-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
