{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}-secrets
  namespace: {{ include "chart.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ include "chart.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ include "chart.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteKey | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
{{- end }}
