{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "chart.fullname" . }}-secret-store
  namespace: {{ include "chart.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ required "project.id is required" .Values.project.id | quote }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.auth.secretName | quote }}
            key: {{ .Values.externalSecrets.auth.secretKey | quote }}
{{- end }}
