apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deploy.serviceAccount.name }}
  namespace: {{ include "chart.namespace" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
